//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDesigner_MVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestReport
    {
        public int ID { get; set; }
        public string ReportName { get; set; }
        public byte[] ReportData { get; set; }
    }
}
